# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(537, 147)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.who_combo = QtWidgets.QComboBox(self.centralwidget)
        self.who_combo.setMinimumSize(QtCore.QSize(169, 0))
        self.who_combo.setEditable(True)
        self.who_combo.setObjectName("who_combo")
        self.verticalLayout_2.addWidget(self.who_combo)
        self.type_combo = QtWidgets.QComboBox(self.centralwidget)
        self.type_combo.setMinimumSize(QtCore.QSize(169, 0))
        self.type_combo.setEditable(True)
        self.type_combo.setObjectName("type_combo")
        self.verticalLayout_2.addWidget(self.type_combo)
        self.group_combo = QtWidgets.QComboBox(self.centralwidget)
        self.group_combo.setMinimumSize(QtCore.QSize(169, 0))
        self.group_combo.setEditable(True)
        self.group_combo.setObjectName("group_combo")
        self.verticalLayout_2.addWidget(self.group_combo)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setMinimumSize(QtCore.QSize(169, 0))
        self.name.setObjectName("name")
        self.verticalLayout_3.addWidget(self.name)
        self.surname = QtWidgets.QLineEdit(self.centralwidget)
        self.surname.setMinimumSize(QtCore.QSize(169, 0))
        self.surname.setObjectName("surname")
        self.verticalLayout_3.addWidget(self.surname)
        self.patronomic = QtWidgets.QLineEdit(self.centralwidget)
        self.patronomic.setMinimumSize(QtCore.QSize(169, 0))
        self.patronomic.setObjectName("patronomic")
        self.verticalLayout_3.addWidget(self.patronomic)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.years = QtWidgets.QLineEdit(self.centralwidget)
        self.years.setMinimumSize(QtCore.QSize(169, 0))
        self.years.setInputMask("")
        self.years.setObjectName("years")
        self.verticalLayout_5.addWidget(self.years)
        self.data_start = QtWidgets.QLineEdit(self.centralwidget)
        self.data_start.setMinimumSize(QtCore.QSize(169, 0))
        self.data_start.setObjectName("data_start")
        self.verticalLayout_5.addWidget(self.data_start)
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setMinimumSize(QtCore.QSize(169, 0))
        self.add_button.setObjectName("add_button")
        self.verticalLayout_5.addWidget(self.add_button)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Админка"))
        self.who_combo.setCurrentText(_translate("MainWindow", "Кого добавить?"))
        self.who_combo.setPlaceholderText(_translate("MainWindow", "Кого добавить?"))
        self.type_combo.setCurrentText(_translate("MainWindow", "Какой тип группы?"))
        self.type_combo.setPlaceholderText(_translate("MainWindow", "Какой тип группы?"))
        self.group_combo.setCurrentText(_translate("MainWindow", "Какая группа?"))
        self.group_combo.setPlaceholderText(_translate("MainWindow", "Какая группа?"))
        self.name.setPlaceholderText(_translate("MainWindow", "Имя"))
        self.surname.setPlaceholderText(_translate("MainWindow", "Фамилия"))
        self.patronomic.setPlaceholderText(_translate("MainWindow", "Отчество"))
        self.years.setPlaceholderText(_translate("MainWindow", "Сколько лет"))
        self.data_start.setPlaceholderText(_translate("MainWindow", "Дата (dd.mm.yyyy)"))
        self.add_button.setText(_translate("MainWindow", "Добавить"))
