# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/card.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(518, 320)
        MainWindow.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setText("")
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.surname = QtWidgets.QLabel(self.centralwidget)
        self.surname.setText("")
        self.surname.setObjectName("surname")
        self.horizontalLayout.addWidget(self.surname)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.patronomic = QtWidgets.QLabel(self.centralwidget)
        self.patronomic.setText("")
        self.patronomic.setObjectName("patronomic")
        self.horizontalLayout.addWidget(self.patronomic)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.year = QtWidgets.QLabel(self.centralwidget)
        self.year.setText("")
        self.year.setObjectName("year")
        self.horizontalLayout.addWidget(self.year)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.timetable = QtWidgets.QTableWidget(self.centralwidget)
        self.timetable.setAutoFillBackground(False)
        self.timetable.setColumnCount(5)
        self.timetable.setObjectName("timetable")
        self.timetable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.timetable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.timetable.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.timetable)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        item = self.timetable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Год"))
        item = self.timetable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Месяц"))
        item = self.timetable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "День"))
        item = self.timetable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Начало"))
        item = self.timetable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Конец"))
